### ISSUE TITLE
Unpermitted Parameters

### ISSUE THREAD

**Issue by lucaswatterson** [kenn/active_flag#16] opened 2021-01-08 18:01 UTC
@kenn, Cheers for what looks to be the perfect solution for my use case.  I followed the README and am attempting to flag two columns, :domains and :venues, on my DataSource model.

`
class DataSource < ApplicationRecord
  flag :domains, [:effectiveness, :suitability, :survivability, :interoperability]
  flag :venues, [:flight_test, :ground_test, :element_testing]
  ...
end
`

DB schema entries as follows....

`
t.integer "domains", default: 0, null: false
t.integer "venues", default: 0, null: false
`

The params are permitted in the controller, form is configured IAW the README and displaying properly, but I get....

`Unpermitted parameter: :domains, :venues`

All other params pass and are saved properly.  Any ideas?  Thank you.

**Comment by kenn** [comment] 2021-01-09 06:32
I'm just guessing here but do you permit those parameters? For instance:

```ruby
params.require(:data_sources).permit(domains: [], venues: [])
```

In any case, this is not a bug of active_flag so I'm going to close this. If you feel it's a bug, feel free to reopen.

**Closed** 2021-01-09 06:33 UTC
